eureka:
    client:
        service-url:
            defaultZone: http://localhost:5000/eureka/
feign:
    hystrix:
        enabled: true
server:
    port: 6004
spring:
    application:
        name: springbootConsumerFeign
